name: CI Build for Affected Projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full Git history is fetched

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build Affected Projects with Dynamic baseHref
      - name: Build Affected Projects
        run: |
          npx nx print-affected --target=build --base=HEAD~1 --select=projects > affected-projects.txt
          cat affected-projects.txt
          while read -r project; do
            echo "Building affected project: $project"
            if [ "$project" = "shell" ]; then
              echo "Building shell app with base-href /"
              npx nx build $project --base-href=/
            else
              echo "Building $project with base-href /shell/$project/"
              npx nx build $project --base-href=/shell/$project/
            fi
          done < affected-projects.txt

      # Step 5: Archive Build Artifacts
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/
